name: New Release

# We only want one release process running for each tag.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
    id-token: write
    contents: read

on:
  push:
    tags:
      - 'v[0-9]*'
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      all_tests: true
    secrets: inherit

  build:
    needs: [tests]
    uses: ./.github/workflows/wheels.yml
    secrets: inherit

  publish:
    needs: [build]
    runs-on: ubuntu-24.04
    steps:
      - name: "Download Wheels from GitHub Artifacts"
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: wheels
          merge-multiple: true
      - name: Publish Wheel to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            packages-dir: "wheels/"
