name: New Release

# We only want one release process running for each tag.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
    id-token: write
    contents: write

on:
  push:
    tags:
      - 'v[0-9]*'
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      all_tests: true
    secrets: inherit

  build:
    needs: [tests]
    uses: ./.github/workflows/wheels.yml
    secrets: inherit

  publish:
    needs: [build]
    runs-on: ubuntu-24.04
    steps:
      - name: "Download Wheels from GitHub Artifacts"
        uses: actions/download-artifact@v8
        with:
          pattern: wheels-*
          path: wheels
          merge-multiple: true
      - name: Publish Wheel to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            packages-dir: "wheels/"
      - uses: actions/checkout@v6
      - name: Publish GitHub Release
        env:
          TITLE: "${{ github.ref_name }}"
          BODY: "Full changelog available [here](https://docs.zubanls.com/en/latest/changelog.html)"
          COMMIT: "${{ github.sha }}"
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "$BODY" > $RUNNER_TEMP/notes.txt
          gh release create "${{ github.ref_name }}" --target "$COMMIT" --title "$TITLE" --notes-file "$RUNNER_TEMP/notes.txt"
